version: '3'

volumes:
  vol_jenkins_home:
    driver: local

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - vol_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/bin/docker-compose